### PR TITLE
moves low cell label up  to match Max Cell temp

### LINKED ISSUE #217: Max Temp Label should be below the data
The format should match all the adjacent labels
image
This occurs in the display mode

### PR DESCRIPTION
**Pull request by nicholasc120**
image

fixes #217 and #218

### CODE REVIEW

**Comment by bill-luu** [comment]
Is that Max text bolded, or is it just me?

**Comment by nicholasc120** [comment]
It is bold, its fixed in pr #227

**Comment by bill-luu** [comment]
Fix up the merge conflicts

**Comment by bill-luu** [comment]
Continued in #232

**Pull request closed without merging**
