### PR TITLE
Removes Tool Tip from Hovering Over the mppt Tab in the Debug Display

### LINKED ISSUE #179: Empty Tool Tip for MPPT tab in Debug Display
When you mouse over the MPPT tab in the Debug Display and don't move for a while, an empty tool tip will pop up
image

### PR DESCRIPTION
**Pull request by nicholasc120**
fixes #179

### CODE REVIEW

**Comment by bill-luu** [comment]
Does the tool tip issue happen with the other buttons too?

**Comment by bill-luu** [comment]
Does the tool tip issue happen with the other buttons too?

**Comment by nicholasc120** [comment]
> Does the tool tip issue happen with the other buttons too?

No, just with the MPPT tab button on the debug display

**Comment by bill-luu** [comment]
Confirmed on my laptop :)

**Pull request merged**
