### PR TITLE
Fix for High DPI Screens

### PR DESCRIPTION
**Pull request by LiamConway**

### CODE REVIEW

**Comment by bill-luu** [comment]
Format!

**Comment by Mavestri** [comment]
> Format!

Not sure how the formatting is breaking - the file's spacing appears different in the Files Changed tab vs View File directly.

**Comment by bill-luu** [comment]
Run it and you'll see. Pretty sure it's the macro that's mis-formatted.

**Comment by ThomasVy** [comment]
I ran the format.sh for you

**Comment by LiamConway** [comment]
@ThomasVy My hero :fireworks: Thanks

**Pull request merged**
